spring:
  application:
    name: mango_diary
  datasource:
    url: jdbc:postgresql://localhost:5432/mango_diary_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379